### ISSUE TITLE
How to use on already installed game

### ISSUE THREAD

**Issue by imlevi** [phaicm/RagnarokOnlineWine#1]
How would one go about using this script for a folder that was already installed? I tried to modify the script and then use it with a folder that i got from a pserver and i'm getting some errors. Not sure if there could be issues when trying to run it like that as i imagine the installer modifies the registry in the process.

**Comment by phaicm** [comment]
This script is meant for new installations for admins to provide.

For general users, you should be able to modify if needed. It does not do anything special other than the recommended steps to run Ragnarok Online. You can manually enter the same commands found in the script if need be.
